/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [
    {
      type: 'category',
      label: 'Start Here',
      collapsed: false,
      link: { type: 'doc', id: 'concepts/overview' },
      items: [
        { type: 'doc', id: 'concepts/ring-protocol', label: 'How Ring Works' },
        { type: 'doc', id: 'concepts/few-protocol', label: 'Few Protocol and FewToken' },
        { type: 'doc', id: 'contracts/overview', label: 'Contract Map' },
        {
          type: 'category',
          label: 'AMM Basics',
          collapsed: true,
          items: ['concepts/protocol/swaps', 'concepts/protocol/fees'],
        },
        'concepts/glossary',
        'concepts/resources',
      ],
    },
    {
      type: 'category',
      label: 'Ring Swap (v2)',
      collapsed: false,
      link: { type: 'doc', id: 'contracts/v2/overview' },
      items: [
        { type: 'doc', id: 'contracts/v2/deployments', label: 'Contract Deployments' },
        { type: 'doc', id: 'contracts/v2/pools', label: 'Pools by Network' },
        {
          type: 'category',
          label: 'FewToken Wrapping',
          collapsed: true,
          link: { type: 'doc', id: 'contracts/v2/fewtoken/integrating' },
          items: [
            'contracts/v2/fewtoken/get-fewtoken-address-via-fewfactory',
            'contracts/v2/fewtoken/how-to-judge-is-few-token',
            'contracts/v2/fewtoken/get-erc20-token-address-via-fewfactory',
          ],
        },
        {
          type: 'category',
          label: 'Concepts',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'contracts/v2/concepts/how-ring-swap-works/ring-swap-model',
              label: 'AMM Model',
            },
            {
              type: 'doc',
              id: 'contracts/v2/concepts/how-ring-swap-works/smart-contracts',
              label: 'Architecture',
            },
            { type: 'doc', id: 'contracts/v2/concepts/core-concepts/swaps', label: 'Swaps' },
            { type: 'doc', id: 'contracts/v2/concepts/core-concepts/pools', label: 'Pools' },
          ],
        },
        {
          type: 'category',
          label: 'Integration Guides',
          collapsed: true,
          items: [
            'contracts/v2/guides/smart-contract-integration/quick-start',
            'contracts/v2/guides/smart-contract-integration/trading-from-a-smart-contract',
            'contracts/v2/guides/smart-contract-integration/providing-liquidity',
            'contracts/v2/guides/smart-contract-integration/getting-pair-addresses',
          ],
        },
        {
          type: 'category',
          label: 'Technical Reference',
          collapsed: true,
          items: [
            'contracts/v2/reference/smart-contracts/factory',
            'contracts/v2/reference/smart-contracts/pair',
            'contracts/v2/reference/smart-contracts/Pair-ERC-20',
            'contracts/v2/reference/smart-contracts/library',
            'contracts/v2/reference/smart-contracts/router-02',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Uniswap v4 Integration',
      collapsed: true,
      link: { type: 'doc', id: 'contracts/v4/overview' },
      items: [
        { type: 'doc', id: 'contracts/v4/deployments', label: 'Upstream Uniswap Deployments' },
        {
          type: 'category',
          label: 'Ring Integration Guides',
          collapsed: true,
          items: [
            'contracts/v4/guides/fewtoken-liquidity-aggregation',
            'contracts/v4/guides/hooks/few-hook-contracts',
            'contracts/v4/guides/hooks/your-first-hook',
            'contracts/v4/guides/hooks/hook-deployment',
            'contracts/v4/guides/read-pool-state',
          ],
        },
        {
          type: 'category',
          label: 'Selected Concepts',
          collapsed: true,
          items: [
            'contracts/v4/concepts/hooks',
            'contracts/v4/concepts/dynamic-fees',
            'contracts/v4/concepts/security',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Build',
      collapsed: true,
      link: { type: 'doc', id: 'build-with-ring/overview' },
      items: [
        {
          type: 'category',
          label: 'Ring Swap SDK',
          collapsed: false,
          link: { type: 'doc', id: 'sdk/v2/overview' },
          items: [
            { type: 'autogenerated', dirName: 'sdk/v2/guides' },
            { type: 'autogenerated', dirName: 'sdk/v2/reference' },
          ],
        },
        {
          type: 'category',
          label: 'SDK Core',
          collapsed: true,
          link: { type: 'doc', id: 'sdk/core/overview' },
          items: [{ type: 'autogenerated', dirName: 'sdk/core/reference' }],
        },
        { type: 'doc', id: 'api/routing/overview', label: 'Routing API' },
      ],
    },
    {
      type: 'category',
      label: 'Ring Wallet',
      collapsed: true,
      link: { type: 'doc', id: 'wallet/overview' },
      items: [
        'wallet/install-pwa',
        {
          type: 'category',
          label: 'Integrate a dApp',
          collapsed: true,
          link: { type: 'doc', id: 'wallet/integrate-dapp/integrate-dapp-overview' },
          items: [
            'wallet/integrate-dapp/register-your-dapp',
            'wallet/integrate-dapp/dapp-integration',
            'wallet/integrate-dapp/dapp-integration-with-skills',
            'wallet/integrate-dapp/test-your-dapp',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Universal Router',
          collapsed: true,
          link: { type: 'doc', id: 'contracts/universal-router/overview' },
          items: ['contracts/universal-router/technical-reference'],
        },
        {
          type: 'category',
          label: 'Permit2',
          collapsed: true,
          link: { type: 'doc', id: 'contracts/permit2/overview' },
          items: ['contracts/permit2/reference/signature-transfer', 'contracts/permit2/reference/allowance-transfer'],
        },
        { type: 'doc', id: 'security-and-risk', label: 'Security and Risk' },
        { type: 'doc', id: 'llms/overview', label: 'AI and LLM Resources' },
      ],
    },
  ],
}

module.exports = sidebars
